version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${MASTER_DB_NAME}
      POSTGRES_USER: ${MASTER_DB_USER}
      POSTGRES_PASSWORD: ${MASTER_DB_PASS}
      TZ: ${TZ}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/logs
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h 127.0.0.1 -U ${MASTER_DB_USER} -d ${MASTER_DB_NAME}" ]
      interval: 30s
      timeout: 30s
      retries: 3
  backend:
    image: golang-boilerplate
    build:
      context: ./
      target: local
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - .:/go/src/app
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      db:
        condition: service_healthy
