openapi: "3.0.0"
info:
  version: 1.0.0
  title: go-boilerplate
  description: TODO
  termsOfService: https://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: https://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080

tags:
  - name: user
    description: User operations

paths:
  /users:
    $ref: ./assets/path/users/root.yaml
  /user:
    $ref: ./assets/path/user/root.yaml
  /user/{id}:
    $ref: ./assets/path/user/[id]/root.yaml

components:
  parameters:
    # Parameter
    UserIdParameter:
      $ref: ./assets/schema/parameter/UserIdParameter.yaml

  schemas:
    # Request
    PostUserRequest:
      $ref: ./assets/schema/request/user/PostUserRequest.yaml
    PutUserRequest:
      $ref: ./assets/schema/request/user/PutUserRequest.yaml

    # Response
    ErrorResponse:
      $ref: ./assets/schema/response/_shared/ErrorResponse.yaml
    UserResponse:
      $ref: ./assets/schema/response/user/UserResponse.yaml
