// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/hum2/backend/internal/interface/controller/batch"
	hellowire2 "github.com/hum2/backend/internal/interface/controller/batch/hellowire"
	"github.com/hum2/backend/internal/usecase/batch/hellowire"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	usecase := hellowire.New()
	lambdaController := hellowire2.New(usecase)
	app := NewApp(lambdaController)
	return app, nil
}

// wire.go:

type App struct {
	Ctr batch.LambdaController
}

func NewApp(
	ctr batch.LambdaController,
) *App {
	return &App{
		Ctr: ctr,
	}
}

var WireSet = wire.NewSet(hellowire.New, hellowire2.New, NewApp)
